### ISSUE TITLE
Custom font with spaces in name doesn't show in preview text of Settings

### ISSUE THREAD

**Issue by stulees** [Rise-Vision/widget-settings-ui-components#269]
**What is not working/What is currently happening**:
When you enter a custom font that contains spaces in the font name it doesn't show in the preview text.

http://rise-vision.github.io/widget-settings-ui-components/#/font-setting

Custom font: https://storage.googleapis.com/risemedialibrary-a9dbdcf0-00c2-45c6-aa6e-14933558ec46/Presentation%20Assets/Trade%20Gothic%20LT%20Bold.ttf

**What is expected to work/What is the client expecting**:
The custom font displays in the preview text

**Comment by alanclayton** [comment]
Fixed with https://github.com/Rise-Vision/widget-settings-ui-components/pull/270
